# Generated by Django 4.0 on 2023-10-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_interest_user_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes',
            new_name='user_saved_news',
        ),
    ]
