# Generated by Django 4.0 on 2023-11-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
        ('accounts', '0004_userclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_news_historic',
            field=models.ManyToManyField(blank=True, related_name='historic', to='reader.News'),
        ),
        migrations.DeleteModel(
            name='UserClick',
        ),
    ]
