# Generated by Django 4.0 on 2023-11-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
        ('accounts', '0005_user_user_news_historic_delete_userclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_last_news',
            field=models.ManyToManyField(blank=True, related_name='last_news', to='reader.News'),
        ),
    ]
