# Generated by Django 4.0 on 2023-11-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_remove_news_is_active'),
        ('accounts', '0006_user_user_last_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_saved_news',
            field=models.ManyToManyField(blank=True, related_name='saved_news', to='reader.News'),
        ),
    ]
